language: node_js
sudo:
  - false
node_js:
  - "6.1"
services:
  - mongodb
env:
  - NODE_ENV=test TRAVIS=travis CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
